# Change these first
owner: graph-technologies # Your GitHub organization or username, where this repository lives
repo: service-monitor # The name of this repository

git:
  commitUser: "github-actions[bot]"
  commitEmail: "41898282+github-actions[bot]@users.noreply.github.com"

sites:
  - name: Graph Technologies
    url: https://graphtechnologies.xyz
  - name: Graph Technologies - Contact
    url: https://graphtechnologies.xyz/contact
  - name: Clara
    url: https://clara.graphtechnologies.xyz
  - name: Graph Technologies GitHub
    url: https://github.com/graph-technologies
  - name: Graph Technologies LinkedIn
    url: https://www.linkedin.com/company/graph-technologies-dk
    expectedStatusCodes:
      - 200
      - 999

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: graphtechnologies.xyz
  baseUrl: /service-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Graph Technologies Status
  introTitle: "**Graph Technologies** Service Status"
  introMessage: This status page monitors the availability and performance of Graph Technologies services using **real-time** data from our [GitHub repository](https://github.com/graph-technologies/service-monitor).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
